"""Add indexes to game box score

Revision ID: 0e5641fb7e7e
Revises: ea5a863958b7
Create Date: 2025-03-01 23:44:06.532452

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e5641fb7e7e"
down_revision: Union[str, None] = "ea5a863958b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_game_box_score", "game", ["box_score"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_game_rhe", "game", ["rhe"], unique=False, postgresql_using="gin"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_game_rhe", table_name="game", postgresql_using="gin")
    op.drop_index("ix_game_box_score", table_name="game", postgresql_using="gin")
    # ### end Alembic commands ###
