"""add columns to game

Revision ID: f48f726c30cd
Revises: 7ab65f4f065a
Create Date: 2025-03-25 22:52:54.188735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f48f726c30cd"
down_revision: Union[str, None] = "7ab65f4f065a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game", sa.Column("balldontlie_id", sa.Integer(), nullable=True))
    op.add_column("game", sa.Column("status", sa.String(), nullable=True))
    op.alter_column(
        "game", "box_score", existing_type=postgresql.ARRAY(sa.INTEGER()), nullable=True
    )
    op.alter_column(
        "game", "rhe", existing_type=postgresql.ARRAY(sa.INTEGER()), nullable=True
    )
    op.alter_column("game", "is_scorhegami", existing_type=sa.BOOLEAN(), nullable=True)
    op.create_index(
        op.f("ix_game_balldontlie_id"), "game", ["balldontlie_id"], unique=True
    )
    op.drop_index("ix_team_balldontlie_id", table_name="team")
    op.create_index(
        op.f("ix_team_balldontlie_id"), "team", ["balldontlie_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_team_balldontlie_id"), table_name="team")
    op.create_index("ix_team_balldontlie_id", "team", ["balldontlie_id"], unique=False)
    op.drop_index(op.f("ix_game_balldontlie_id"), table_name="game")
    op.alter_column("game", "is_scorhegami", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "game", "rhe", existing_type=postgresql.ARRAY(sa.INTEGER()), nullable=False
    )
    op.alter_column(
        "game",
        "box_score",
        existing_type=postgresql.ARRAY(sa.INTEGER()),
        nullable=False,
    )
    op.drop_column("game", "status")
    op.drop_column("game", "balldontlie_id")
    # ### end Alembic commands ###
