"""add index to game status

Revision ID: 5fd2a1509432
Revises: f48f726c30cd
Create Date: 2025-03-26 21:49:51.491526

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5fd2a1509432"
down_revision: Union[str, None] = "f48f726c30cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_game_status"), "game", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_game_status"), table_name="game")
    # ### end Alembic commands ###
