"""db setup

Revision ID: 70505e806ca6
Revises:
Create Date: 2025-03-19 22:58:58.890525

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "70505e806ca6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("short_name", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("short_name"),
    )
    op.create_table(
        "game",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("away_id", sa.Integer(), nullable=False),
        sa.Column("home_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.TIMESTAMP(), nullable=True),
        sa.Column("end_time", sa.TIMESTAMP(), nullable=True),
        sa.Column("box_score", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("rhe", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("is_scorhegami", sa.Boolean(), nullable=False),
        sa.CheckConstraint("home_id != away_id", name="different_teams_constraint"),
        sa.ForeignKeyConstraint(
            ["away_id"],
            ["team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_game_box_score", "game", ["box_score"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_game_rhe", "game", ["rhe"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_unique_game",
        "game",
        ["home_id", "away_id", "start_time"],
        unique=True,
        postgresql_where=sa.text("start_time IS NOT NULL"),
    )
    op.create_table(
        "scorhegami_game",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scorhegami_game")
    op.drop_index(
        "ix_unique_game",
        table_name="game",
        postgresql_where=sa.text("start_time IS NOT NULL"),
    )
    op.drop_index("ix_game_rhe", table_name="game", postgresql_using="gin")
    op.drop_index("ix_game_box_score", table_name="game", postgresql_using="gin")
    op.drop_table("game")
    op.drop_table("team")
    # ### end Alembic commands ###
