"""add game balldontlie id

Revision ID: 7d5e98368207
Revises: 7ab65f4f065a
Create Date: 2025-03-25 21:34:43.048567

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d5e98368207"
down_revision: Union[str, None] = "7ab65f4f065a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game", sa.Column("balldontlie_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_game_balldontlie_id"), "game", ["balldontlie_id"], unique=True
    )

    op.drop_index("ix_team_balldontlie_id", table_name="team")
    op.create_index(
        op.f("ix_team_balldontlie_id"), "team", ["balldontlie_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_team_balldontlie_id"), table_name="team")
    op.create_index("ix_team_balldontlie_id", "team", ["balldontlie_id"], unique=False)

    op.drop_index(op.f("ix_game_balldontlie_id"), table_name="game")
    op.drop_column("game", "balldontlie_id")
    # ### end Alembic commands ###
