"""balldontlie_id

Revision ID: 417788913996
Revises: 70505e806ca6
Create Date: 2025-03-23 13:57:54.436001

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "417788913996"
down_revision: Union[str, None] = "70505e806ca6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team", sa.Column("balldontlie_id", sa.Integer(), nullable=True))

    op.add_column(
        "team",
        sa.Column("is_most_recent_name", sa.Boolean(), nullable=True),
    )
    op.execute(
        """
        UPDATE team SET is_most_recent_name = FALSE;
        """
    )
    op.alter_column("team", "is_most_recent_name", nullable=False)

    op.drop_constraint("team_short_name_key", "team", type_="unique")
    op.create_index(
        op.f("ix_team_balldontlie_id"), "team", ["balldontlie_id"], unique=False
    )
    op.create_index(
        "ix_unique_most_recent_name",
        "team",
        ["balldontlie_id", "is_most_recent_name"],
        unique=False,
        postgresql_where=sa.text("is_most_recent_name IS true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_unique_most_recent_name",
        table_name="team",
        postgresql_where=sa.text("is_most_recent_name IS true"),
    )
    op.drop_index(op.f("ix_team_balldontlie_id"), table_name="team")
    op.create_unique_constraint("team_short_name_key", "team", ["short_name"])
    op.drop_column("team", "is_most_recent_name")
    op.drop_column("team", "balldontlie_id")
    # ### end Alembic commands ###
