"""drop scorhegami_game table

Revision ID: c7de74688edc
Revises: f477ce2d0caa
Create Date: 2025-03-31 23:57:12.396335

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7de74688edc"
down_revision: Union[str, None] = "f477ce2d0caa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scorhegami_game")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scorhegami_game",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"], ["game.id"], name="scorhegami_game_game_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="scorhegami_game_pkey"),
    )
    # ### end Alembic commands ###
