"""add game date

Revision ID: 75a3a103f168
Revises: 8dff340c1513
Create Date: 2025-04-26 16:58:07.851515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75a3a103f168"
down_revision: Union[str, None] = "8dff340c1513"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game", sa.Column("game_date", sa.DATE(), nullable=True))

    op.execute(
        """
        UPDATE game
        SET game_date = 
            CASE 
                WHEN EXTRACT(YEAR FROM start_time) < 2025 THEN start_time::DATE
                ELSE (start_time AT TIME ZONE 'UTC' - INTERVAL '7 hours')::DATE
            END;
        """
    )

    op.alter_column("game", "game_date", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game", "game_date")
    # ### end Alembic commands ###
