"""initial db setup

Revision ID: ea5a863958b7
Revises:
Create Date: 2025-02-02 02:06:48.060248

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ea5a863958b7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("short_name", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("short_name"),
    )
    op.create_index(op.f("ix_team_id"), "team", ["id"], unique=False)
    op.create_table(
        "game",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("away_id", sa.Uuid(), nullable=False),
        sa.Column("home_id", sa.Uuid(), nullable=False),
        sa.Column("start_time", sa.TIMESTAMP(), nullable=True),
        sa.Column("box_score", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("rhe", sa.ARRAY(sa.Integer()), nullable=False),
        sa.CheckConstraint("home_id != away_id", name="different_teams_constraint"),
        sa.ForeignKeyConstraint(
            ["away_id"],
            ["team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_game_id"), "game", ["id"], unique=False)
    op.create_index(
        "ix_unique_game",
        "game",
        ["home_id", "away_id", "start_time"],
        unique=True,
        postgresql_where=sa.text("start_time IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_unique_game",
        table_name="game",
        postgresql_where=sa.text("start_time IS NOT NULL"),
    )
    op.drop_index(op.f("ix_game_id"), table_name="game")
    op.drop_table("game")
    op.drop_index(op.f("ix_team_id"), table_name="team")
    op.drop_table("team")
    # ### end Alembic commands ###
