"""timezone aware

Revision ID: 7ab65f4f065a
Revises: 9e68bae8e94f
Create Date: 2025-03-25 01:57:53.173625

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ab65f4f065a"
down_revision: Union[str, None] = "9e68bae8e94f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game", sa.Column("start_time_tz", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.add_column(
        "game", sa.Column("end_time_tz", sa.TIMESTAMP(timezone=True), nullable=True)
    )

    # Convert and copy data - assuming existing timestamps are in UTC
    # This will convert naive timestamps to UTC timezone-aware timestamps
    op.execute(
        """
        UPDATE
            game
        SET
            start_time_tz = start_time AT TIME ZONE 'UTC',
            end_time_tz = end_time AT TIME ZONE 'UTC'
        """
    )

    # Drop old columns
    op.drop_column("game", "start_time")
    op.drop_column("game", "end_time")

    # Rename new columns to replace old ones
    op.alter_column("game", "start_time_tz", new_column_name="start_time")
    op.alter_column("game", "end_time_tz", new_column_name="end_time")

    # Recreate indices that depend on these columns
    op.create_index(
        "ix_unique_game",
        "game",
        ["home_id", "away_id", "start_time"],
        unique=True,
        postgresql_where=sa.text("start_time IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create temporary columns without timezone info
    op.add_column(
        "game",
        sa.Column("start_time_notz", sa.TIMESTAMP(timezone=False), nullable=True),
    )
    op.add_column(
        "game", sa.Column("end_time_notz", sa.TIMESTAMP(timezone=False), nullable=True)
    )

    # Convert timezone-aware to timezone-naive
    op.execute(
        """
        UPDATE
            game
        SET
            start_time_notz = start_time AT TIME ZONE 'UTC',
            end_time_notz = end_time AT TIME ZONE 'UTC'
        """
    )

    # Drop timezone-aware columns
    op.drop_column("game", "start_time")
    op.drop_column("game", "end_time")

    # Rename naive columns to original names
    op.alter_column("game", "start_time_notz", new_column_name="start_time")
    op.alter_column("game", "end_time_notz", new_column_name="end_time")

    # Recreate indices
    op.create_index(
        "ix_unique_game",
        "game",
        ["home_id", "away_id", "start_time"],
        unique=True,
        postgresql_where=sa.text("start_time IS NOT NULL"),
    )
    # ### end Alembic commands ###
