"""add baseball reference link

Revision ID: 9e68bae8e94f
Revises: 417788913996
Create Date: 2025-03-24 23:13:15.129177

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e68bae8e94f"
down_revision: Union[str, None] = "417788913996"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game", sa.Column("bref_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game", "bref_url")
    # ### end Alembic commands ###
