"""add tweet status

Revision ID: c1e693828e54
Revises: 66295536869e
Create Date: 2025-04-09 23:45:59.459967

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1e693828e54"
down_revision: Union[str, None] = "66295536869e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tweet", sa.Column("status", sa.String(), nullable=True))
    op.execute(
        """
        UPDATE
            tweet
        SET
            status = CASE
                WHEN tweet_id IS NOT NULL THEN 'success'
                ELSE 'failed'
            END;
        """
    )
    op.alter_column("tweet", "status", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tweet", "status")
    # ### end Alembic commands ###
